=== aureliodel/xml-dtd-xsd/criminales.dtd
<!ELEMENT criminales (criminal)*>

	<!ELEMENT criminal (datos_personales, historial_medico?, historial_penal)>

		<!ELEMENT datos_personales (apellidos_nombre, fecha_nacimiento, altura, descripcion_fisica, direccion_completa)>

			<!ATTLIST datos_personales dni CDATA>
			<!ATTLIST datos_personales sexo (H|M)> 
			<!ELEMENT apellidos_nombre (#PCDATA)>
			<!ELEMENT fecha_nacimiento (#PCDATA)>
			<!ELEMENT altura (#PCDATA)>
			<!ELEMENT descripcion_fisica (#PCDATA)>

			<!ELEMENT direccion_completa (direccion, localidad, codigo_postal, provincia)>

				<!ELEMENT direccion (#PCDATA)>
				!ELEMENT localidad (#PCDATA)>
				<!ELEMENT codigo_postal (#PCDATA)>
				<!ELEMENT provincia (#PCDATA)>

		<!ELEMENT historial_medico (#PCDATA)>

		<!ELEMENT historial_penal (estado_de_libertad, delitos_cometidos, juzagado, pena, cumplimiento)>

			<!ELEMENT estado_de_libertad (#PCDATA)>
			<!ELEMENT delitos_cometidos (#PCDATA)>
			<!ELEMENT juzgado (#PCDATA)>
			<!ELEMENT pena (#PCDATA)>
			<!ELEMENT cumplimiento (#PCDATA)>

=== aureliodel/xml-dtd-xsd/criminales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE criminales SYSTEM "criminales.dtd">

<criminales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="criminales.xsd">

	<criminal>

		<datos_personales dni="45784565X" sexo="H">

			<apellidos_nombre>Roba Motos, Mangante</apellidos_nombre>
			<fecha_nacimiento>14/03/2000</fecha_nacimiento>
			<altura>1.82 metros</altura>
			<descripcion_fisica>Persona...</descripcion_fisica>

			<direccion_completa>

				<direccion>Calle Desaparecido</direccion>
				<localidad>Granada</localidad>
				<codigo_postal>18145</codigo_postal>
				<provincia>Granada</provincia>

			</direccion_completa>

		</datos_personales>

		<historial_medico></historial_medico>

		<historial_penal>

			<estado_de_libertad>Preso</estado_de_libertad>
			<delitos_cometidos>Robo con violencia e intimidación</delitos_cometidos>
			<juzagado>SI</juzagado>
			<pena>5 años</pena>
			<cumplimiento>SI</cumplimiento>

		</historial_penal>

	</criminal>

</criminales>
