=== aureliodel/xml-dtd-xsd/fabrica.dtd
<!ELEMENT fabrica (pieza*, obrero*, pintor*, ensamblador*, chapista*, coche*)>

	<!ELEMENT pieza (origen, nombre, peso, stock)>
		
		<!ATTLIST pieza referencia ID #REQUIRED>
		<!ELEMENT origen (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT peso (#PCDATA)>
		<!ELEMENT stock (#PCDATA)>

	<!ELEMENT obrero (dni, nombre, apellidos, direccion, localidad, codigo_postal, provincia, fecha_incorporacion)>
		
		<!ATTLIST obrero cod_trabajador ID #REQUIRED> 
		<!ELEMENT dni (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT direccion(#PCDATA)>
		<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT codigo_postal (#PCDATA)>
		<!ELEMENT provincia (#PCDATA)>
		<!ELEMENT fecha_incorporacion (#PCDATA)>

	<!ELEMENT pintor (dni, nombre, apellidos, direccion, localidad, codigo_postal, provincia, fecha_incorporacion, fecha_examen)>
		
		<!ATTLIST pintor cod_trabajador ID #REQUIRED> 
		<!ELEMENT dni (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT direccion(#PCDATA)>
		<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT codigo_postal (#PCDATA)>
		<!ELEMENT provincia (#PCDATA)>
		<!ELEMENT fecha_incorporacion (#PCDATA)>
		<!ELEMENT fecha_examen (#PCDATA)>

	<!ELEMENT ensamblador (dni, nombre, apellidos, direccion, localidad, codigo_postal, provincia, fecha_incorporacion)>
		
		<!ATTLIST ensamblador cod_trabajador ID #REQUIRED> 
		<!ELEMENT dni (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT direccion(#PCDATA)>
		<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT codigo_postal (#PCDATA)>
		<!ELEMENT provincia (#PCDATA)>
		<!ELEMENT fecha_incorporacion (#PCDATA)>
	
	<!ELEMENT chapista (dni, nombre, apellidos, direccion, localidad, codigo_postal, provincia, fecha_incorporacion)>
		
		<!ATTLIST chapista cod_trabajador ID #REQUIRED> 
		<!ELEMENT dni (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT direccion(#PCDATA)>
		<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT codigo_postal (#PCDATA)>
		<!ELEMENT provincia (#PCDATA)>
		<!ELEMENT fecha_incorporacion (#PCDATA)>

	<!ELEMENT coche (parte_coche, chapa, ensamblado)>

		<!ATTLIST coche bastidor CDATA #REQUIRED>
		<!ELEMENT parte_coche (nombre, componente*)>

			<!ELEMENTE nombre (#PCDATA)>
			<!ELEMENTE componente (montador)>
				
				<!ELEMENTE montador EMPTY>
					
					<!ATTLIST montador cod_t IDREF #REQUIRED>

		<!ELEMENTchapa (chapista, pintado, color)>

			<!ELEMENTE chapista EMPTY>
					
					<!ATTLIST chapsita cod_t IDREF #REQUIRED>

			<!ELEMENTE pintado EMPTY>
					
					<!ATTLIST pintado cod_t IDREF #REQUIRED>

		<!ELEMENTE ensmablado EMPTY>

			<!ATTLIST ensamblado cod_t IDREF #REQUIRED>

=== aureliodel/xml-dtd-xsd/fabrica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fabrica SYSTEM "fabrica.dtd">

<fabrica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fabrica.xsd">

	<pieza referencia="">
		<origen></origen>
		<nombre></nombre>
		<peso></peso>
		<stock></stock>
	</pieza>

	<obrero cod_trabajador="">
		<dni></dni>
		<nombre></nombre>
		<apellidos></apellidos>
		<direccion></direccion>
		<localidad></localidad>
		<codigo_postal></codigo_postal>
		<provincia></provincia>
		<fecha_incorporacion></fecha_incorporacion>
	</obrero>

	<pintor cod_trabajador="">
		<dni></dni>
		<nombre></nombre>
		<apellidos></apellidos>
		<direccion></direccion>
		<localidad></localidad>
		<codigo_postal></codigo_postal>
		<provincia></provincia>
		<fecha_incorporacion></fecha_incorporacion>
		<fecha_examen></fecha_examen>
	</pintor>

	<ensamblador cod_trabajador="">
		<dni></dni>
		<nombre></nombre>
		<apellidos></apellidos>
		<direccion></direccion>
		<localidad></localidad>
		<codigo_postal></codigo_postal>
		<provincia></provincia>
		<fecha_incorporacion></fecha_incorporacion>
	</ensamblador>

	<chapista cod_trabajador="">
		<dni></dni>
		<nombre></nombre>
		<apellidos></apellidos>
		<direccion></direccion>
		<localidad></localidad>
		<codigo_postal></codigo_postal>
		<provincia></provincia>
		<fecha_incorporacion></fecha_incorporacion>
	</chapista>

	<coche bastidor="">
		<parte_coche>
			<nombre></nombre>
			<componente ref="">
				<montador cod_t=""></montador>
			</componente>	
		</parte_coche>
		<chapa>
			<chapista cod_t=""></chapista>
			<pintado cod_t=""></pintado>
			<color></color>
		</chapa>
		<ensamblado codigo_t=""></ensamblado>
	</coche>


</fabrica>
